### ISSUE TITLE
Html Validation Issue

### ISSUE THREAD

**Issue by kaybow** [kaybow/dsn1675-assignment-1#1]
Hi Thomas,

I'm still tweaking my site; as I checked my html in the validator, it said I cannot have a <div> as a child element of a <dl>— so what can I use to contain my dd's & dt's?

Thanks!
Kayla

@thomasjbradley

<img width="742" alt="screen shot 2015-09-18 at 9 37 17 pm" src="https://cloud.githubusercontent.com/assets/10467661/9974015/79f1b1e6-5e4d-11e5-9bf9-2a8856ea85e0.png">

**Comment by kaybow** [comment]
*div as a child element of a dl

**Comment by thomasjbradley** [comment]
Unfortunately nothing can be done about that, there can't be any element directly inside the `<dl>` except `<dt>` and `<dd>`. You'll have to find another solution. What look are you trying to accomplish?

**Comment by kaybow** [comment]
Just to float each element beside each other. I am happy with how it looks otherwise. I'll ask around what others have done, thank you.
